name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip<=23.0.1
  - pip:
      - mlflow
      - cloudpickle
      - numpy
      - pandas
      - scikit-learn
      - scipy