name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip<=23.0.1
  - pip:
      - mlflow==2.12.1
      - cloudpickle==3.1.1
      - numpy==2.2.6
      - pandas==2.3.0
      - scikit-learn==1.7.0
      - scipy==1.15.3