name: Train ML Model

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.17

    - name: Install pip & dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MLProject/requirements.txt
        pip install mlflow

    - name: Run MLflow Project
      run: mlflow run MLProject